name: ezifresh-pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/ezifresh/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  CI: true
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Generate APK
        run: |
          yarn build:android --filter ezifresh

      - name: Cache APK build artifacts
        uses: actions/cache@v3
        with:
          path: ezifreshartifacts
          key: ${{ runner.os }}-apk-${{ hashFiles('**/android/app/build.gradle', '**/android/gradle-wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-apk-

      - name: Upload a Build Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ezifresh
          path: ezifreshartifacts/**
          if-no-files-found: error
          retention-days: 30
          overwrite: true

      - name: Create finished comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue-number: ${{github.event.pull_request.number}}
          body: |
            🎉 There is a new version of [ezifresh](${{steps.upload-artifact.outputs.artifact-url}}).
