name: Create Ezifresh Preview

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/ezifresh/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  CI: true

jobs:
  # Job 1: Setup Environment
  setup:
    runs-on: ubuntu-latest
    name: Setup Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and Yarn
        run: npm install -g yarn

  # Job 2: Install Dependencies with Caching
  install_dependencies:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install project dependencies
        run: yarn install

  # Job 3: Build Application with EAS and Caching
  build_app:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@8.0.0
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Expo apps
        run: |
          yarn install 
          npx expo prebuild --clean

      - name: Generate APK
        run: |
          eas build --local --p android --profile development --output=ezifreshartifacts/android.apk

      - name: Cache APK build artifacts
        uses: actions/cache@v3
        with:
          path: ezifreshartifacts
          key: ${{ runner.os }}-apk-${{ hashFiles('**/android/app/build.gradle', '**/android/gradle-wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-apk-

      - name: Upload a Build Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ezifresh
          path: ezifreshartifacts/**
          if-no-files-found: error
          retention-days: 30
          overwrite: true

  # Job 5: Post Build Actions
  post_build:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - name: Create finished comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue-number: ${{github.event.pull_request.number}}
          body: |
            🎉 There is a new version of [ezifresh](${{steps.upload-artifact.outputs.artifact-url}}).
